datasource:
    url: jdbc:mysql://localhost:3306/test        
    #原文 luochengroot    
    username: '{cipher}5320cc1c35cd237a2849869e645456c6aa356ef27e7f2bd80f6ac44963e56a14'
    #原文luocheng123456
    password: '{cipher}AQBJJUtZ86TNSXdGftSZCio24WOllFMhmmd4MRk4DpWFsWGWnYvLZfLP4dv+tF3oeaNd/u3EaxlJj0WqTorPVtFHCLog8yHFEhD07uOVDBVmA9u2pm/Zva1VDocKrcn5KbJDGbfsKGgJnjTJW1HQNhYpMjnAtCa3X62wRYMOrfgs2kKD3JwfsJiLxLzEJ+qe68HRBQdhOXy6LQ1pA+RUr4LrS5QrTSLog8bFZ6e0J4E2QZUqdsKc4UzUwXGHUCH5uszoH4e5VFxTEpqFcU+4mbMlSfghnow+IwYsio4W8CB100fATctN2T0jWJNz7oQB/ZoBSubqGlP9u8mhW/yu1JLDFyJxZwh0FHqT2WNCV3gtQXh3EI91V+yBo+I7YpMQwns='
    #oa地址http://oa.hkfs.cn/
    公司地址: '{cipher}3b1fa3a447d3548229e5ca080076c877efe54410d17d7ce024ce6f1f138fab1661a21df91110266639507ff8a007e7ad'

