datasource:
    url: jdbc:mysql://localhost:3306/test        
    #原文luocheng
    password: '{cipher}AQBJJUtZ86TNSXdGftSZCio24WOllFMhmmd4MRk4DpWFsWGWnYvLZfLP4dv+tF3oeaNd/u3EaxlJj0WqTorPVtFHCLog8yHFEhD07uOVDBVmA9u2pm/Zva1VDocKrcn5KbJDGbfsKGgJnjTJW1HQNhYpMjnAtCa3X62wRYMOrfgs2kKD3JwfsJiLxLzEJ+qe68HRBQdhOXy6LQ1pA+RUr4LrS5QrTSLog8bFZ6e0J4E2QZUqdsKc4UzUwXGHUCH5uszoH4e5VFxTEpqFcU+4mbMlSfghnow+IwYsio4W8CB100fATctN2T0jWJNz7oQB/ZoBSubqGlP9u8mhW/yu1JLDFyJxZwh0FHqT2WNCV3gtQXh3EI91V+yBo+I7YpMQwns='


